name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
gravatar:
  size: 80
  sizeM: 50
  sizeS: 30
session:
  remem: 1
contact:
  url: http://www.railstutorial.org/contact
password_reset_time:
  max_time: 2
content:
  maximum: 140
picture:
  max_size: 5
  type: "image/jpeg,image/gif,image/png"
